name: brt
channels:
    - pytorch
    - huggingface
    - conda-forge
    - defaults
dependencies:
    - python>=3.9
    - pip>=22
    - pytorch>=1.10
    - transformers
    - ipykernel
    - einops
    - datasets
    - pip:
        - jupyterlab
        - polars
        - pytest
        - torchtyping
        - typeguard
        - x-transformers==0.27.0
        - wandb
    